exports.cekResi = require('./cekResi')
exports.meme = require('./meme')
exports.urlShortener = require('./shortener')
exports.translate = require('./translate')
exports.getLocationData = require('./location')
exports.menuId = require('./menu/id')
exports.wallpaper = require('./wall.js')
